version: '3.7'
services:
  studio:
    build:
      dockerfile: ./studio/Dockerfile
      context: .
    ports:
      - 8410:3333
    volumes:
      - ./studio:/app

  web:
    build:
      dockerfile: ./web/Dockerfile
      context: .
    ports:
      - 8420:3000
    volumes:
      - ./web:/app
